# Generated by Django 5.0.2 on 2024-03-04 10:39

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_playlist_created_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=None, editable=False, null=True, populate_from="username"
            ),
        ),
    ]
